name: digital_pet_app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting package
  flutter_lints: ^5.0.0

flutter:
  # Ensures Material Icons font is included
  uses-material-design: true

  # Asset files for the app
  assets:
    - assets/pet.png
    - assets/pet-background.jpg
    - assets/feed_background.jpg
    - assets/play_background.jpg
